---Tabla Convenios


CREATE TABLE   CONVENIOS  
   (	 CVN_ID  NUMBER(*,0) DEFAULT   CVN_SEQ . NEXTVAL  CONSTRAINT  CVN_ID_NN_CK  NOT NULL ENABLE, 
	 CVN_NOMBRE  VARCHAR2(45) CONSTRAINT "CVN_NOMBRE_NN_CK" NOT NULL ENABLE, 
	"CVN_ALIAS" VARCHAR2(15), 
	"CVN_C_HORAS" NUMBER DEFAULT 5, 
	"CVN_POR_FDO_DES1" NUMBER(6,2), 
	"CVN_FDO_DES2" NUMBER(6,2), 
	"CVN_VALOR_AUMENTO" NUMBER(10,2), 
	"CVN_POR_AUMENTO_DECREP" NUMBER(10,2), 
	"CVN_C_LEGAL" VARCHAR2(30), 
	"CVN_INCLUYE_ANTIGUEDAD" VARCHAR2(1), 
	"CVN_T_DIAS_LEGALES" VARCHAR2(1), 
	"CVN_MES_GOCE_VAC_D" NUMBER, 
	"CVN_Q_DIAS" NUMBER, 
	"CVN_CONC_SUE_BASE" NUMBER, 
	"CVN_CLAVE_EXTERNA" VARCHAR2(100), 
	 CONSTRAINT "CVN_ID_PK" PRIMARY KEY ("CVN_ID")
  USING INDEX  ENABLE
   )
/


---Personal_categorias (estaba mal, lo guardo por las dudas) 

CREATE TABLE  "PERSONAL_CATEGORIAS" 
   (	"CCT_ID" NUMBER(*,0) DEFAULT  "CCT_SEQ"."NEXTVAL" CONSTRAINT "CCT_ID_NN_CK" NOT NULL ENABLE, 
	"CCT_C_CONVENIO" VARCHAR2(30), 
	"CCT_D_CONVENIO" VARCHAR2(45), 
	"CCT_A_CONVENIO" VARCHAR2(15), 
	"CCT_D_CATEGORIAS" VARCHAR2(45), 
	"CCT_M_OTRO_VALOR" NUMBER, 
	"CCT_M_POR_DIA" NUMBER, 
	"CCT_M_POR_MES" NUMBER, 
	"CCT_A_CATEGORIA" VARCHAR2(15), 
	"CCT_C_ARTICULO" VARCHAR2(13), 
	"CCT_B_MASIVA" VARCHAR2(1), 
	"CCT_UTILIDAD" NUMBER(15,5), 
	"CCT_Q_DIAS_LEGALES" NUMBER(15,2), 
	"CCT_Q_DIAS_SINDICALES" NUMBER(15,2), 
	"CCT_C_LEGAL" VARCHAR2(30), 
	"CCT_NIVEL_INFERIOR" VARCHAR2(1), 
	"CCT_CLAVE_EXTERNA" VARCHAR2(100), 
	"CCT_CVN_ID" NUMBER, 
	 CONSTRAINT "CCT_ID_PK" PRIMARY KEY ("CCT_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "PERSONAL_CATEGORIAS" ADD CONSTRAINT "CCT_CVN_FK" FOREIGN KEY ("CCT_CVN_ID")
	  REFERENCES  "CONVENIOS" ("CVN_ID") ENABLE
/



--Convenios_categorias


CREATE TABLE  "CONVENIOS_CATEGORIAS" 
   (
    "CCT_ID" NUMBER(*,0) DEFAULT  "CCT_SEQ"."NEXTVAL" CONSTRAINT "CCT_ID_NN_CK" NOT NULL ENABLE, 
	"CCT_C_CONVENIO" VARCHAR2(30), 
	"CCT_D_CONVENIO" VARCHAR2(45), 
	"CCT_A_CONVENIO" VARCHAR2(15), 
	"CCT_D_CATEGORIAS" VARCHAR2(45), 
	"CCT_M_OTRO_VALOR" NUMBER, 
	"CCT_M_POR_DIA" NUMBER, 
	"CCT_M_POR_MES" NUMBER, 
	"CCT_A_CATEGORIA" VARCHAR2(15), 
	"CCT_C_ARTICULO" VARCHAR2(13), 
	"CCT_B_MASIVA" VARCHAR2(1), 
	"CCT_UTILIDAD" NUMBER(15,5), 
	"CCT_Q_DIAS_LEGALES" NUMBER(15,2), 
	"CCT_Q_DIAS_SINDICALES" NUMBER(15,2), 
	"CCT_C_LEGAL" VARCHAR2(30), 
	"CCT_NIVEL_INFERIOR" VARCHAR2(1), 
	"CCT_CLAVE_EXTERNA" VARCHAR2(100), 
	"CCT_CVN_ID" NUMBER, 
	 CONSTRAINT "CCT_ID_PK" PRIMARY KEY ("CCT_ID")
  USING INDEX  ENABLE
   )
/
ALTER TABLE  "CONVENIOS_CATEGORIAS" ADD CONSTRAINT "CCT_CVN_FK" FOREIGN KEY ("CCT_CVN_ID")
	  REFERENCES  "CONVENIOS" ("CVN_ID") ENABLE
/





  CREATE TABLE "CONVENIOS_CATEGORIAS"(
  "CCT_ID" NUMBER(*,0) DEFAULT  "CCT_SEQ"."NEXTVAL" CONSTRAINT "CCT_ID_NN_CK" NOT NULL ENABLE,
  "CCT_NOMBRE" Varchar2(45 ) NOT NULL,
  "CCT_CODIGO_CONVENIO" Varchar2(30 ),
  "CCT_A_CONVENIO" Varchar2(15 ),
  "CCT_D_CATEGORIAS" Varchar2(45 ),
  "CCT_M_OTRO_VALOR" Number,
  "CCT_M_POR_DIA" Number,
  "CCT_M_POR_MES" Number,
  "CCT_A_CATEGORIA" Varchar2(15 ),
  "CCT_C_ARTICULO" Varchar2(13 ),
  "CCT_B_MASIVA" Varchar2(1 ),
  "CCT_UTILIDAD" Number(15,5),
  "CCT_Q_DIAS_LEGALES" Number(15,2),
  "CCT_Q_DIAS_SINDICALES" Number(15,2),
  "CCT_C_LEGAL" Varchar2(30 ),
  "CCT_NIVEL_INFERIOR" Varchar2(1 ),
  "CCT_CLAVE_EXTERNA" Varchar2(100 ),
  "CCT_A_PERSONAS" Varchar2(2 ),
  "CCT_NIVEL_F_ANTIGUEDAD" Varchar2(2 ),
  "CCT_CVN_ID" Number DEFAULT  "CVN_SEQ"."NEXTVAL"
)
/

-- Create indexes for table CONVENIOS_CATEGORIAS

CREATE INDEX "CCT_CVN_ID_IX" ON "CONVENIOS_CATEGORIAS" ("CCT_CVN_ID")
/

-- Add keys for table CONVENIOS_CATEGORIAS

ALTER TABLE "CONVENIOS_CATEGORIAS" ADD CONSTRAINT "CCT_ID_PK" PRIMARY KEY ("CCT_ID")
/




alter table "PERSONAL_CATEGORIAS" add
(
	
	-- PCT_COEF_EVALUACION_DESEMP  NUMBER,
    -- PCT_F_GRABACION  DATE,
	-- PCT_Q_DIAS_LEGALES  NUMBER,
	-- PCT_Q_DIAS_SINDICALES  NUMBER,
	-- PCT_Q_DIAS_CONTRATO  NUMBER,
	-- PCT_T_MONEDA  VARCHAR2(1),
	--PCT_C_VALOR  NUMBER,
	--PCT_T_F_MONEDA  VARCHAR2(1),
	 --PCT_M_OTRO_VALOR_ME  NUMBER,
	 --PCT_M_POR_DIA_ME  NUMBER,
	 --PCT_M_POR_MES_ME  NUMBER,
	 --PCT_F_MODIFICACION  DATE,

   
 )


