DECLARE
CURSOR NOMBRES IS SELECT DEPARTMENT_NAME FROM DEPARTMENTS order by DEPARTMENT_NAME;
BEGIN
FOR C IN NOMBRES LOOP
DBMS_OUTPUT.PUT_LINE('DEPARTAMENTO CON NOMBRE: ' || C.DEPARTMENT_NAME);
END LOOP;
END;



