



--TABLA PERSONAL_CATEGORIAS

CREATE TABLE "PERSONAL_CATEGORIAS"(
  "PCT_ID" Number (*,0) DEFAULT  "PCT_SEQ"."NEXTVAL" CONSTRAINT "PCT_ID_NN_CK" NOT NULL ENABLE,
  "PCT_C_CONVENIO" Varchar2(30 ) NOT NULL,
  "PCT_D_CONVENIO" Varchar2(45 ) CONSTRAINT "PCT_D_CONVENIO_NN_CK" NOT NULL ENABLE,
  "PCT_A_CONVENIO" Varchar2(15 ),
  "PCT_D_CATEGORIAS" Varchar2(45 ),
  "PCT_M_OTRO_VALOR" Number,
  "PCT_M_POR_DIA" Number,
  "PCT_M_POR_MES" Number,
  "PCT_A_CATEGORIA" Varchar2(15 ),
  "PCT_C_ARTICULO" Varchar2(13 ),
  "PCT_B_MASIVA" Varchar2(1 ),
  "PCT_UTILIDAD" Number(15,5),
  "PCT_Q_DIAS_LEGALES" Number(15,2),
  "PCT_Q_DIAS_SINDICALES" Number(15,2),
  "PCT_C_LEGAL" Varchar2(30 ),
  "PCT_NIVEL_INFERIOR" Varchar2(1 ),
  "PCT_TSU_ID" Integer,
  CONSTRAINT "PCT_ID_PK" PRIMARY KEY ("PCT_ID")
  USING INDEX ENABLE
)


--TABLA CONVENIOS


-- Table CONVENIOS

CREATE TABLE "CONVENIOS"(
  "CVN_ID" Number (*,0) DEFAULT "CVN_SEQ"."NEXTVAL" CONSTRAINT "CVN_ID_NN_CK" NOT NULL ENABLE,
  "CVN_NOMBRE" Varchar2(45 ) CONSTRAINT "CVN_NOMBRE_NN_CK" NOT NULL ENABLE,
  "CVN_ALIAS" Varchar2(15 ),
  "CVN_C_HORAS" Number DEFAULT 5,
  "CVN_POR_FDO_DES1" Number(6,2),
  "CVN_FDO_DES2" Number(6,2),
  "CVN_VALOR_AUMENTO" Number(10,2),
  "CVN_POR_AUMENTO_DECREP" Number(10,2),
  "CVN_C_LEGAL" Varchar2(30 ),
  "CVN_INCLUYE_ANTIGUEDAD" Varchar2(1 ),
  "CVN_T_DIAS_LEGALES" Varchar2(1 ),
  "CVN_MES_GOCE_VAC_D" Number,
  "CVN_Q_DIAS" Number,
  "CVN_CONC_SUE_BASE" Number,
  "CVN_CLAVE_EXTERNA" Varchar2(100 ),
  CONSTRAINT "CVN_ID_PK" PRIMARY KEY ("CVN_ID")
  USING INDEX ENABLE

)

CREATE TABLE "ESPECIES"(
"ESP_ID" NUMBER(*,0) DEFAULT "ESP_SEQ"."NEXTVAL" CONSTRAINT "ESP_ID_NN_CK" NOT NULL ENABLE,
"ESP_NOMBRE" Varchar2(45) CONSTRAINT "ESP_NOMBRE_NN_CK" NOT NULL ENABLE,
CONSTRAINT "ESP_ID_PK" PRIMARY KEY ("ESP_ID")
USING INDEX ENABLE
)


--------------------------------
CREATE TABLE "PERSONAL_CATEGORIAS"(
  "PCT_ID" Number (*,0) DEFAULT  "PCT_SEQ"."NEXTVAL" CONSTRAINT "PCT_ID_NN_CK" NOT NULL ENABLE,
  "PCT_C_CONVENIO" Varchar2(30 ) NOT NULL,
  "PCT_D_CONVENIO" Varchar2(45 ) CONSTRAINT "PCT_D_CONVENIO_NN_CK" NOT NULL ENABLE,
  "PCT_A_CONVENIO" Varchar2(15 ),
  "PCT_D_CATEGORIAS" Varchar2(45 ),
  "PCT_M_OTRO_VALOR" Number,
  "PCT_M_POR_DIA" Number,
  "PCT_M_POR_MES" Number,
  "PCT_A_CATEGORIA" Varchar2(15 ),
  "PCT_C_ARTICULO" Varchar2(13 ),
  "PCT_B_MASIVA" Varchar2(1 ),
  "PCT_UTILIDAD" Number(15,5),
  "PCT_Q_DIAS_LEGALES" Number(15,2),
  "PCT_Q_DIAS_SINDICALES" Number(15,2),
  "PCT_C_LEGAL" Varchar2(30 ),
  "PCT_NIVEL_INFERIOR" Varchar2(1 ),
  "PCT_TSU_ID" Integer,
  CONSTRAINT "PCT_ID_PK" PRIMARY KEY ("PCT_ID")
  USING INDEX ENABLE
)





-- Table PERSONAL_CATEGORIAS

CREATE TABLE "PERSONAL_CATEGORIAS"(
  "PCT_ID" Number (*,0) DEFAULT  "PCT_SEQ"."NEXTVAL" CONSTRAINT "PCT_ID_NN_CK" NOT NULL ENABLE,
  "PCT_NOMBRE" Varchar2(45) CONSTRAINT "PCT_NOMBRE_NN_CK" NOT NULL ENABLE,
  "PCT_F_CATEGORIA" Date,
  "PCT_CVN_ID" integer,
  "PCT_CCT_ID" integer,
  "PCT_SUJ_ID" Integer,
  CONSTRAINT "PCT_ID_PK" PRIMARY KEY ("PCT_ID")
  USING INDEX ENABLE
)


ALTER TABLE "PERSONAL_CATEGORIAS" ADD CONSTRAINT "PCT_SUJ_FK" FOREIGN KEY ("PCT_SUJ_ID") REFERENCES "SUJETOS" ("SUJ_ID")




-- Table PERSONALES_SECTORES

CREATE TABLE "PERSONALES_SECTORES"(
  "PSE_ID" Number (*,0) DEFAULT "PSE_SEQ"."NEXTVAL" CONSTRAINT "PSE_ID_NN_CK" NOT NULL ENABLE,
  "PSE_SEC_ID" Integer,
  "PSE_SUJ_ID" Integer,
  "PSE_FECHA_DESDE" Date,
  "PSE_DECHA_HASTA" Date,
  "PSE_OBSERVACIONES" Varchar2(60 ),
  "PSE_M_PACTADO" Number(12,2),
  "PSE_TIPO_M_PACTADO" Varchar2(1 ),
  "PSE_CALIFICACION" Number,
  "PSE_CLAVE_EXTERNA" Varchar2(100 ),
  CONSTRAINT "PSE_ID_PK" PRIMARY KEY ("PSE_ID")
  USING INDEX ENABLE
)



select SUJ_APELLIDO ||' '|| SUJ_NOMBRE as d,
       SUJ_ID as r
  from SUJETOS
 order by 1



 SELECT SUJ_ID,
	SUJ_TIPO_PERSONA,
	SUJ_ID_FISCAL,
	SUJ_NOMBRE,
	SUJ_APELLIDO,
	SUJ_ESTADO
FROM SUJETOS 
where SUJ_ID in (SELECT SUP_SUJ_ID 
				 FROM SUJETOS_PERFILES
	--			 Where SUP_PER_ID = :P80_PERFIL)
                Where SUP_PER_ID = 18)           --Cod 18 perfil PERSONAL - tabla Perfiles







 SELECT S SEC_ID,
 FROM SUJETOS 
 where SUJ_ID in (SELECT SUP_SUJ_ID 
         				 FROM SUJETOS_PERFILES
	--		      	 Where SUP_PER_ID = :P80_PERFIL)
                 Where SUP_PER_ID = 18)           --Cod 18 perfil PERSONAL - tabla Perfiles




